version: "3.2"

services:

  api:
    build: ./images/api
    container_name: api
    command: ["npm", "run", "prep"]
    ports:
      - 3000:3000
    volumes:
      - ./images/api/src:/usr/app/src
      - ./images/api/db:/usr/app/db
    environment:
      PG_CONNECTION_STRING: "postgres://test:test@store:5432/test"
    depends_on:
      store:
        condition: service_healthy
  
  store:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test "]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./_volumes/testtore:/var/lib/postgresql/data