version: "3.2"

services:

  api:
    build: ./images/api
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - ./images/api/src:/usr/app/src
      - ./images/api/db:/usr/app/db
    environment:
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@store:5432/${POSTGRES_DB}"
    depends_on:
      store:
        condition: service_healthy
  
  store:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
      POSTGRES_HOST_AUTH_METHOD:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB "]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./_volumes/store:/var/lib/postgresql/data